### ISSUE TITLE
the example doesn't work?

### ISSUE THREAD

**Issue by bburdette** [rsignavong/elm-leaflet-map#3]
if I run it with elm-reactor I just get some text, no map.

**Comment by rsignavong** [comment]
Yes this elm package only put the html tag on browser and the example make sure of it.
elm-reactor doesn't allow to run a package with an npm module.
You have to add the webcomponent https://www.npmjs.com/package/stencil-leaflet-component to make it works.
I don't have no more time to work on it. You are free to fork it.
